"""
This type stub file was generated by pyright.
"""

from ..util import registry
@registry.architectures.register("thinc.FeedForward.v1")
def FeedForward(config): ...
@registry.architectures.register("spacy.LayerNormalizedMaxout.v1")
def LayerNormalizedMaxout(config): ...
