"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def ner_jsonl2json(
    input_data, lang: Optional[Any] = ..., n_sents=..., use_morphology: bool = ..., **_
): ...
def _cleanup_spans(spans): ...
