"""
This type stub file was generated by pyright.
"""

from thinc.api import layerize

def Tok2Vec(width, embed_size, **kwargs): ...
@layerize
def flatten(seqs, drop=...): ...
def concatenate_lists(*layers, **kwargs):
    """Compose two or more models `f`, `g`, etc, such that their outputs are
    concatenated, i.e. `concatenate(f, g)(x)` computes `hstack(f(x), g(x))`
    """
    ...
