"""
This type stub file was generated by pyright.
"""

from thinc.api import layerize

def concatenate_lists(*layers, **kwargs):
    """Compose two or more models `f`, `g`, etc, such that their outputs are
    concatenated, i.e. `concatenate(f, g)(x)` computes `hstack(f(x), g(x))`
    """
    ...

@layerize
def flatten(seqs, drop=...):
    ...

