"""
This type stub file was generated by pyright.
"""

from ..util import registry

@registry.architectures.register("spacy.Tok2Vec.v1")
def Tok2Vec(config):
    ...

@registry.architectures.register("spacy.Doc2Feats.v1")
def Doc2Feats(config):
    ...

@registry.architectures.register("spacy.MultiHashEmbed.v1")
def MultiHashEmbed(config):
    ...

@registry.architectures.register("spacy.CharacterEmbed.v1")
def CharacterEmbed(config):
    ...

@registry.architectures.register("spacy.MaxoutWindowEncoder.v1")
def MaxoutWindowEncoder(config):
    ...

@registry.architectures.register("spacy.MishWindowEncoder.v1")
def MishWindowEncoder(config):
    ...

@registry.architectures.register("spacy.PretrainedVectors.v1")
def PretrainedVectors(config):
    ...

@registry.architectures.register("spacy.TorchBiLSTMEncoder.v1")
def TorchBiLSTMEncoder(config):
    ...

_EXAMPLE_CONFIG = { "@doc2feats": { "arch": "Doc2Feats","config": { "columns": ["ID", "NORM", "PREFIX", "SUFFIX", "SHAPE", "ORTH"] } },"@embed": { "arch": "spacy.MultiHashEmbed.v1","config": { "width": 96,"rows": 2000,"columns": ["ID", "NORM", "PREFIX", "SUFFIX", "SHAPE", "ORTH"],"use_subwords": True,"@pretrained_vectors": { "arch": "TransformedStaticVectors","config": { "vectors_name": "en_vectors_web_lg.vectors","width": 96,"column": 0 } },"@mix": { "arch": "LayerNormalizedMaxout","config": { "width": 96,"pieces": 3 } } } },"@encode": { "arch": "MaxoutWindowEncode","config": { "width": 96,"window_size": 1,"depth": 4,"pieces": 3 } } }
