"""
This type stub file was generated by pyright.
"""

from __future__ import unicode_literals

import sys
import warnings
from typing import Any, Optional

from thinc.neural.util import prefer_gpu, require_gpu

from . import pipeline, util
from .about import __version__
from .cli.info import info as cli_info
from .errors import Errors, Warnings, deprecation_warning
from .glossary import explain
from .language import Language, component
from .util import registry

if sys.maxunicode == 65535: ...

def load(name: str, **overrides: Any) -> Language: ...
def blank(name: str, **kwargs: Any) -> Language: ...
def info(model: Optional[Any] = ..., markdown: bool = ..., silent: bool = ...): ...

__all__ = ["load", "blank", "info", "component"]
