"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def conllu2json(input_data, n_sents=..., use_morphology: bool = ..., lang: Optional[Any] = ..., **_):
    """
    Convert conllu files into JSON format for use with train cli.
    use_morphology parameter enables appending morphology to tags, which is
    useful for languages such as Spanish, where UD tags are not so rich.

    Extract NER tags if available and convert them so that they follow
    BILUO and the Wikipedia scheme
    """
    ...

def is_ner(tag):
    """
    Check the 10th column of the first token to determine if the file contains
    NER tags
    """
    ...

def read_conllx(input_data, use_morphology: bool = ..., n=...):
    ...

def simplify_tags(iob):
    """
    Simplify tags obtained from the dataset in order to follow Wikipedia
    scheme (PER, LOC, ORG, MISC). 'PER', 'LOC' and 'ORG' keep their tags, while
    'GPE_LOC' is simplified to 'LOC', 'GPE_ORG' to 'ORG' and all remaining tags to
    'MISC'.
    """
    ...

def generate_sentence(sent, has_ner_tags):
    ...

def create_doc(sentences, id):
    ...

