"""
This type stub file was generated by pyright.
"""

def validate():
    """
    Validate that the currently installed version of spaCy is compatible
    with the installed models. Should be run after `pip install -U spacy`.
    """
    ...

def get_model_links(compat):
    ...

def get_model_pkgs(compat, all_models):
    ...

def get_model_row(compat, name, data, msg, model_type=...):
    ...

def is_model_path(model_path):
    ...

def is_compat(compat, name, version):
    ...

def reformat_version(version):
    """Hack to reformat old versions ending on '-alpha' to match pip format."""
    ...

