ACADEMIC = "ACADEMIC"
AGE = "AGE"
AIRCRAFT = "AIRCRAFT"
AIRPORT = "AIRPORT"
AMPHIBIA = "AMPHIBIA"
AMUSEMENT_PARK = "AMUSEMENT_PARK"
ANIMAL_DISEASE = "ANIMAL_DISEASE"
ANIMAL_PART = "ANIMAL_PART"
ARCHAEOLOGICAL_PLACE_OTHER = "ARCHAEOLOGICAL_PLACE_OTHER"
ART_OTHER = "ART_OTHER"
ASTRAL_BODY_OTHER = "ASTRAL_BODY_OTHER"
AWARD = "AWARD"
BAY = "BAY"
BIRD = "BIRD"
BOOK = "BOOK"
BRIDGE = "BRIDGE"
BROADCAST_PROGRAM = "BROADCAST_PROGRAM"
CABINET = "CABINET"
CALORIE = "CALORIE"
CANAL = "CANAL"
CAR = "CAR"
CAR_STOP = "CAR_STOP"
CHARACTER = "CHARACTER"
CITY = "CITY"
CLASS = "CLASS"
CLOTHING = "CLOTHING"
COLOR_OTHER = "COLOR_OTHER"
COMPANY = "COMPANY"
COMPANY_GROUP = "COMPANY_GROUP"
COMPOUND = "COMPOUND"
CONFERENCE = "CONFERENCE"
CONSTELLATION = "CONSTELLATION"
CONTINENTAL_REGION = "CONTINENTAL_REGION"
CORPORATION_OTHER = "CORPORATION_OTHER"
COUNTRY = "COUNTRY"
COUNTX_OTHER = "COUNTX_OTHER"
COUNTY = "COUNTY"
CULTURE = "CULTURE"
CURRENCY = "CURRENCY"
DATE = "DATE"
DAY_OF_WEEK = "DAY_OF_WEEK"
DECORATION = "DECORATION"
DISEASE_OTHER = "DISEASE_OTHER"
DISH = "DISH"
DOCTRINE_METHOD_OTHER = "DOCTRINE_METHOD_OTHER"
DOMESTIC_REGION = "DOMESTIC_REGION"
DRUG = "DRUG"
EARTHQUAKE = "EARTHQUAKE"
ELEMENT = "ELEMENT"
EMAIL = "EMAIL"
ERA = "ERA"
ETHNIC_GROUP_OTHER = "ETHNIC_GROUP_OTHER"
EVENT_OTHER = "EVENT_OTHER"
FACILITY_OTHER = "FACILITY_OTHER"
FACILITY_PART = "FACILITY_PART"
FAMILY = "FAMILY"
FISH = "FISH"
FLORA = "FLORA"
FLORA_PART = "FLORA_PART"
FOOD = "FOOD"
FOOD_OTHER = "FOOD_OTHER"
FREGUENCY = "FREGUENCY"
FREQUENCY = "FREQUENCY"
FUNGUS = "FUNGUS"
GOE_OTHER = "GOE_OTHER"
GPE_OTHER = "GPE_OTHER"
GAME = "GAME"
GEOLOGICAL_REGION_OTHER = "GEOLOGICAL_REGION_OTHER"
GOD = "GOD"
GOVERNMENT = "GOVERNMENT"
ID_NUMBER = "ID_NUMBER"
INCIDENT_OTHER = "INCIDENT_OTHER"
INSECT = "INSECT"
INTENSITY = "INTENSITY"
INTERNATIONAL_ORGANIZATION = "INTERNATIONAL_ORGANIZATION"
ISLAND = "ISLAND"
LAKE = "LAKE"
LANGUAGE_OTHER = "LANGUAGE_OTHER"
LATITUDE_LONGTITUDE = "LATITUDE_LONGTITUDE"
LAW = "LAW"
LINE_OTHER = "LINE_OTHER"
LIVING_THING_OTHER = "LIVING_THING_OTHER"
LIVING_THING_PART_OTHER = "LIVING_THING_PART_OTHER"
LOCATION_OTHER = "LOCATION_OTHER"
MAGAZINE = "MAGAZINE"
MAMMAL = "MAMMAL"
MARKET = "MARKET"
MATERIAL = "MATERIAL"
MEASUREMENT_OTHER = "MEASUREMENT_OTHER"
MILITARY = "MILITARY"
MINERAL = "MINERAL"
MOLLUSC_ARTHROPOD = "MOLLUSC_ARTHROPOD"
MONEY = "MONEY"
MONEY_FORM = "MONEY_FORM"
MOUNTAIN = "MOUNTAIN"
MOVEMENT = "MOVEMENT"
MOVIE = "MOVIE"
MULTIPLICATION = "MULTIPLICATION"
MUSEUM = "MUSEUM"
MUSIC = "MUSIC"
N_ANIMAL = "N_ANIMAL"
N_COUNTRY = "N_COUNTRY"
N_EVENT = "N_EVENT"
N_FACILITY = "N_FACILITY"
N_FLORA = "N_FLORA"
N_LOCATION_OTHER = "N_LOCATION_OTHER"
N_NATURAL_OBJECT_OTHER = "N_NATURAL_OBJECT_OTHER"
N_ORGANIZATION = "N_ORGANIZATION"
N_PERSON = "N_PERSON"
N_PRODUCT = "N_PRODUCT"
NAME_OTHER = "NAME_OTHER"
NATIONAL_LANGUAGE = "NATIONAL_LANGUAGE"
NATIONALITY = "NATIONALITY"
NATURAL_DISASTER = "NATURAL_DISASTER"
NATURAL_OBJECT_OTHER = "NATURAL_OBJECT_OTHER"
NATURAL_PHENOMENON_OTHER = "NATURAL_PHENOMENON_OTHER"
NATURE_COLOR = "NATURE_COLOR"
NEWSPAPER = "NEWSPAPER"
NUMEX_OTHER = "NUMEX_OTHER"
OCCASION_OTHER = "OCCASION_OTHER"
OFFENCE = "OFFENCE"
OFFENSE = "OFFENSE"
ORDINAL_NUMBER = "ORDINAL_NUMBER"
ORGANIZATION_OTHER = "ORGANIZATION_OTHER"
PARK = "PARK"
PERCENT = "PERCENT"
PERIOD_DAY = "PERIOD_DAY"
PERIOD_MONTH = "PERIOD_MONTH"
PERIOD_TIME = "PERIOD_TIME"
PERIOD_WEEK = "PERIOD_WEEK"
PERIOD_YEAR = "PERIOD_YEAR"
PERIOD_TIME = "PERIOD_TIME"
PERIODX_OTHER = "PERIODX_OTHER"
PERSON = "PERSON"
PHONE_NUMBER = "PHONE_NUMBER"
PHYSICAL_EXTENT = "PHYSICAL_EXTENT"
PICTURE = "PICTURE"
PLAN = "PLAN"
PLANET = "PLANET"
POINT = "POINT"
POLITICAL_ORGANIZATION_OTHER = "POLITICAL_ORGANIZATION_OTHER"
POLITICAL_PARTY = "POLITICAL_PARTY"
PORT = "PORT"
POSITION_VOCATION = "POSITION_VOCATION"
POSITION_VOCATION = "POSITION_VOCATION"
POSTAL_ADDRESS = "POSTAL_ADDRESS"
PRINTING_OTHER = "PRINTING_OTHER"
PRO_SPORTS_ORGANIZATION = "PRO_SPORTS_ORGANIZATION"
PRODUCT_OTHER = "PRODUCT_OTHER"
PROVINCE = "PROVINCE"
PUBLIC_INSTITUTION = "PUBLIC_INSTITUTION"
RAILROAD = "RAILROAD"
RANK = "RANK"
REGION_OTHER = "REGION_OTHER"
RELIGION = "RELIGION"
RELIGIOUS_FESTIVAL = "RELIGIOUS_FESTIVAL"
REPTILE = "REPTILE"
RESEARCH_INSTITUTE = "RESEARCH_INSTITUTE"
RIVER = "RIVER"
ROAD = "ROAD"
RULE_OTHER = "RULE_OTHER"
SCHOOL = "SCHOOL"
SCHOOL_AGE = "SCHOOL_AGE"
SEA = "SEA"
SEISMIC_INTENSITY = "SEISMIC_INTENSITY"
SHIP = "SHIP"
SHOW = "SHOW"
SHOW_ORGANIZATION = "SHOW_ORGANIZATION"
SPA = "SPA"
SPACE = "SPACE"
SPACESHIP = "SPACESHIP"
SPEED = "SPEED"
SPORT = "SPORT"
SPORTS_FACILITY = "SPORTS_FACILITY"
SPORTS_LEAGUE = "SPORTS_LEAGUE"
SPORTS_ORGANIZATION_OTHER = "SPORTS_ORGANIZATION_OTHER"
STAR = "STAR"
STATION = "STATION"
STOCK = "STOCK"
STOCK_INDEX = "STOCK_INDEX"
STYLE = "STYLE"
TEMPERATURE = "TEMPERATURE"
THEATER = "THEATER"
THEORY = "THEORY"
TIME = "TIME"
TIME_TOP_OTHER = "TIME_TOP_OTHER"
TIMEX_OTHER = "TIMEX_OTHER"
TITLE_OTHER = "TITLE_OTHER"
TRAIN = "TRAIN"
TREATY = "TREATY"
TUMULUS = "TUMULUS"
TUNNEL = "TUNNEL"
URL = "URL"
UNIT_OTHER = "UNIT_OTHER"
VEHICLE_OTHER = "VEHICLE_OTHER"
VOLUME = "VOLUME"
WAR = "WAR"
WATER_ROUTE = "WATER_ROUTE"
WEAPON = "WEAPON"
WEIGHT = "WEIGHT"
WORSHIP_PLACE = "WORSHIP_PLACE"
ZOO = "ZOO"

ALL_LABELS = [
    ACADEMIC,
    AGE,
    AIRCRAFT,
    AIRPORT,
    AMPHIBIA,
    AMUSEMENT_PARK,
    ANIMAL_DISEASE,
    ANIMAL_PART,
    ARCHAEOLOGICAL_PLACE_OTHER,
    ART_OTHER,
    ASTRAL_BODY_OTHER,
    AWARD,
    BAY,
    BIRD,
    BOOK,
    BRIDGE,
    BROADCAST_PROGRAM,
    CABINET,
    CALORIE,
    CANAL,
    CAR,
    CAR_STOP,
    CHARACTER,
    CITY,
    CLASS,
    CLOTHING,
    COLOR_OTHER,
    COMPANY,
    COMPANY_GROUP,
    COMPOUND,
    CONFERENCE,
    CONSTELLATION,
    CONTINENTAL_REGION,
    CORPORATION_OTHER,
    COUNTRY,
    COUNTX_OTHER,
    COUNTY,
    CULTURE,
    CURRENCY,
    DATE,
    DAY_OF_WEEK,
    DECORATION,
    DISEASE_OTHER,
    DISH,
    DOCTRINE_METHOD_OTHER,
    DOMESTIC_REGION,
    DRUG,
    EARTHQUAKE,
    ELEMENT,
    EMAIL,
    ERA,
    ETHNIC_GROUP_OTHER,
    EVENT_OTHER,
    FACILITY_OTHER,
    FACILITY_PART,
    FAMILY,
    FISH,
    FLORA,
    FLORA_PART,
    FOOD,
    FOOD_OTHER,
    FREGUENCY,
    FREQUENCY,
    FUNGUS,
    GOE_OTHER,
    GPE_OTHER,
    GAME,
    GEOLOGICAL_REGION_OTHER,
    GOD,
    GOVERNMENT,
    ID_NUMBER,
    INCIDENT_OTHER,
    INSECT,
    INTENSITY,
    INTERNATIONAL_ORGANIZATION,
    ISLAND,
    LAKE,
    LANGUAGE_OTHER,
    LATITUDE_LONGTITUDE,
    LAW,
    LINE_OTHER,
    LIVING_THING_OTHER,
    LIVING_THING_PART_OTHER,
    LOCATION_OTHER,
    MAGAZINE,
    MAMMAL,
    MARKET,
    MATERIAL,
    MEASUREMENT_OTHER,
    MILITARY,
    MINERAL,
    MOLLUSC_ARTHROPOD,
    MONEY,
    MONEY_FORM,
    MOUNTAIN,
    MOVEMENT,
    MOVIE,
    MULTIPLICATION,
    MUSEUM,
    MUSIC,
    N_ANIMAL,
    N_COUNTRY,
    N_EVENT,
    N_FACILITY,
    N_FLORA,
    N_LOCATION_OTHER,
    N_NATURAL_OBJECT_OTHER,
    N_ORGANIZATION,
    N_PERSON,
    N_PRODUCT,
    NAME_OTHER,
    NATIONAL_LANGUAGE,
    NATIONALITY,
    NATURAL_DISASTER,
    NATURAL_OBJECT_OTHER,
    NATURAL_PHENOMENON_OTHER,
    NATURE_COLOR,
    NEWSPAPER,
    NUMEX_OTHER,
    OCCASION_OTHER,
    OFFENCE,
    OFFENSE,
    ORDINAL_NUMBER,
    ORGANIZATION_OTHER,
    PARK,
    PERCENT,
    PERIOD_DAY,
    PERIOD_MONTH,
    PERIOD_TIME,
    PERIOD_WEEK,
    PERIOD_YEAR,
    PERIOD_TIME,
    PERIODX_OTHER,
    PERSON,
    PHONE_NUMBER,
    PHYSICAL_EXTENT,
    PICTURE,
    PLAN,
    PLANET,
    POINT,
    POLITICAL_ORGANIZATION_OTHER,
    POLITICAL_PARTY,
    PORT,
    POSITION_VOCATION,
    POSITION_VOCATION,
    POSTAL_ADDRESS,
    PRINTING_OTHER,
    PRO_SPORTS_ORGANIZATION,
    PRODUCT_OTHER,
    PROVINCE,
    PUBLIC_INSTITUTION,
    RAILROAD,
    RANK,
    REGION_OTHER,
    RELIGION,
    RELIGIOUS_FESTIVAL,
    REPTILE,
    RESEARCH_INSTITUTE,
    RIVER,
    ROAD,
    RULE_OTHER,
    SCHOOL,
    SCHOOL_AGE,
    SEA,
    SEISMIC_INTENSITY,
    SHIP,
    SHOW,
    SHOW_ORGANIZATION,
    SPA,
    SPACE,
    SPACESHIP,
    SPEED,
    SPORT,
    SPORTS_FACILITY,
    SPORTS_LEAGUE,
    SPORTS_ORGANIZATION_OTHER,
    STAR,
    STATION,
    STOCK,
    STOCK_INDEX,
    STYLE,
    TEMPERATURE,
    THEATER,
    THEORY,
    TIME,
    TIME_TOP_OTHER,
    TIMEX_OTHER,
    TITLE_OTHER,
    TRAIN,
    TREATY,
    TUMULUS,
    TUNNEL,
    URL,
    UNIT_OTHER,
    VEHICLE_OTHER,
    VOLUME,
    WAR,
    WATER_ROUTE,
    WEAPON,
    WEIGHT,
    WORSHIP_PLACE,
    ZOO,
]
