"""
This type stub file was generated by pyright.
"""

import plac
from typing import Any, Optional
@plac.annotations(
    model=("Model to download (shortcut or name)", "positional", None, str),
    direct=("Force direct download of name + version", "flag", "d", bool),
    pip_args="Additional arguments to be passed to `pip install` on model install",
)
def download(model, direct: bool = ..., *pip_args):
    """
    Download compatible model from default download path using pip. Model
    can be shortcut, model name or, if --direct flag is set, full model name
    with version. For direct downloads, the compatibility check will be skipped.
    """
    ...

def require_package(name): ...
def get_json(url, desc): ...
def get_compatibility(): ...
def get_version(model, comp): ...
def download_model(filename, user_pip_args: Optional[Any] = ...): ...
