"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

import plac

@plac.annotations(
    model=("Model name or path", "positional", None, str),
    data_path=("Location of JSON-formatted evaluation data", "positional", None, str),
    gold_preproc=("Use gold preprocessing", "flag", "G", bool),
    gpu_id=("Use GPU", "option", "g", int),
    displacy_path=("Directory to output rendered parses as HTML", "option", "dp", str),
    displacy_limit=("Limit of parses to render as HTML", "option", "dl", int),
    return_scores=("Return dict containing model scores", "flag", "R", bool),
)
def evaluate(
    model,
    data_path,
    gpu_id=...,
    gold_preproc: bool = ...,
    displacy_path: Optional[Any] = ...,
    displacy_limit=...,
    return_scores: bool = ...,
):
    """
    Evaluate a model. To render a sample of parses in a HTML file, set an
    output directory as the displacy_path argument.
    """
    ...

def render_parses(
    docs, output_path, model_name=..., limit=..., deps: bool = ..., ents: bool = ...
): ...
