COLOR = "COLOR"
COLOR_OTHER = "COLOR/COLOR_OTHER"
NATURE_COLOR = "COLOR/NATURE_COLOR"
DISEASE = "DISEASE"
ANIMAL_DISEASE = "DISEASE/ANIMAL_DISEASE"
DISEASE_OTHER = "DISEASE/DISEASE_OTHER"
EVENT = "EVENT"
EVENT_OTHER = "EVENT/EVENT_OTHER"
INCIDENT = "EVENT/INCIDENT"
INCIDENT_OTHER = "EVENT/INCIDENT/INCIDENT_OTHER"
WAR = "EVENT/INCIDENT/WAR"
NATURAL_PHENOMENON = "EVENT/NATURAL_PHENOMENON"
EARTHQUAKE = "EVENT/NATURAL_PHENOMENON/EARTHQUAKE"
NATURAL_DISASTER = "EVENT/NATURAL_PHENOMENON/NATURAL_DISASTER"
NATURAL_PHENOMENON_OTHER = "EVENT/NATURAL_PHENOMENON/NATURAL_PHENOMENON_OTHER"
OCCASION = "EVENT/OCCASION"
CONFERENCE = "EVENT/OCCASION/CONFERENCE"
GAME = "EVENT/OCCASION/GAME"
OCCASION_OTHER = "EVENT/OCCASION/OCCASION_OTHER"
RELIGIOUS_FESTIVAL = "EVENT/OCCASION/RELIGIOUS_FESTIVAL"
FACILITY = "FACILITY"
ARCHAEOLOGICAL_PLACE = "FACILITY/ARCHAEOLOGICAL_PLACE"
ARCHAEOLOGICAL_PLACE_OTHER = "FACILITY/ARCHAEOLOGICAL_PLACE/ARCHAEOLOGICAL_PLACE_OTHER"
TUMULUS = "FACILITY/ARCHAEOLOGICAL_PLACE/TUMULUS"
FACILITY_OTHER = "FACILITY/FACILITY_OTHER"
FACILITY_PART = "FACILITY/FACILITY_PART"
GOE = "FACILITY/GOE"
AIRPORT = "FACILITY/GOE/AIRPORT"
AMUSEMENT_PARK = "FACILITY/GOE/AMUSEMENT_PARK"
CAR_STOP = "FACILITY/GOE/CAR_STOP"
GOE_OTHER = "FACILITY/GOE/GOE_OTHER"
MARKET = "FACILITY/GOE/MARKET"
MUSEUM = "FACILITY/GOE/MUSEUM"
PARK = "FACILITY/GOE/PARK"
PORT = "FACILITY/GOE/PORT"
PUBLIC_INSTITUTION = "FACILITY/GOE/PUBLIC_INSTITUTION"
RESEARCH_INSTITUTE = "FACILITY/GOE/RESEARCH_INSTITUTE"
SCHOOL = "FACILITY/GOE/SCHOOL"
SPORTS_FACILITY = "FACILITY/GOE/SPORTS_FACILITY"
STATION = "FACILITY/GOE/STATION"
THEATER = "FACILITY/GOE/THEATER"
WORSHIP_PLACE = "FACILITY/GOE/WORSHIP_PLACE"
ZOO = "FACILITY/GOE/ZOO"
LINE = "FACILITY/LINE"
BRIDGE = "FACILITY/LINE/BRIDGE"
CANAL = "FACILITY/LINE/CANAL"
LINE_OTHER = "FACILITY/LINE/LINE_OTHER"
RAILROAD = "FACILITY/LINE/RAILROAD"
ROAD = "FACILITY/LINE/ROAD"
TUNNEL = "FACILITY/LINE/TUNNEL"
WATER_ROUTE = "FACILITY/LINE/WATER_ROUTE"
GOD = "GOD"
LOCATION = "LOCATION"
ADDRESS = "LOCATION/ADDRESS"
ADDRESS_OTHER = "LOCATION/ADDRESS/ADDRESS_OTHER"
EMAIL = "LOCATION/ADDRESS/EMAIL"
PHONE_NUMBER = "LOCATION/ADDRESS/PHONE_NUMBER"
POSTAL_ADDRESS = "LOCATION/ADDRESS/POSTAL_ADDRESS"
URL = "LOCATION/ADDRESS/URL"
ASTRAL_BODY = "LOCATION/ASTRAL_BODY"
ASTRAL_BODY_OTHER = "LOCATION/ASTRAL_BODY/ASTRAL_BODY_OTHER"
CONSTELLATION = "LOCATION/ASTRAL_BODY/CONSTELLATION"
PLANET = "LOCATION/ASTRAL_BODY/PLANET"
STAR = "LOCATION/ASTRAL_BODY/STAR"
GEOLOGICAL_REGION = "LOCATION/GEOLOGICAL_REGION"
BAY = "LOCATION/GEOLOGICAL_REGION/BAY"
GEOLOGICAL_REGION_OTHER = "LOCATION/GEOLOGICAL_REGION/GEOLOGICAL_REGION_OTHER"
ISLAND = "LOCATION/GEOLOGICAL_REGION/ISLAND"
LAKE = "LOCATION/GEOLOGICAL_REGION/LAKE"
MOUNTAIN = "LOCATION/GEOLOGICAL_REGION/MOUNTAIN"
RIVER = "LOCATION/GEOLOGICAL_REGION/RIVER"
SEA = "LOCATION/GEOLOGICAL_REGION/SEA"
GPE = "LOCATION/GPE"
CITY = "LOCATION/GPE/CITY"
COUNTRY = "LOCATION/GPE/COUNTRY"
COUNTY = "LOCATION/GPE/COUNTY"
GPE_OTHER = "LOCATION/GPE/GPE_OTHER"
PROVINCE = "LOCATION/GPE/PROVINCE"
LOCATION_OTHER = "LOCATION/LOCATION_OTHER"
REGION = "LOCATION/REGION"
CONTINENTAL_REGION = "LOCATION/REGION/CONTINENTAL_REGION"
DOMESTIC_REGION = "LOCATION/REGION/DOMESTIC_REGION"
REGION_OTHER = "LOCATION/REGION/REGION_OTHER"
SPA = "LOCATION/SPA"
NAME_OTHER = "NAME_OTHER"
NATURAL_OBJECT = "NATURAL_OBJECT"
COMPOUND = "NATURAL_OBJECT/COMPOUND"
ELEMENT = "NATURAL_OBJECT/ELEMENT"
LIVING_THING = "NATURAL_OBJECT/LIVING_THING"
AMPHIBIA = "NATURAL_OBJECT/LIVING_THING/AMPHIBIA"
BIRD = "NATURAL_OBJECT/LIVING_THING/BIRD"
FISH = "NATURAL_OBJECT/LIVING_THING/FISH"
FLORA = "NATURAL_OBJECT/LIVING_THING/FLORA"
FUNGUS = "NATURAL_OBJECT/LIVING_THING/FUNGUS"
INSECT = "NATURAL_OBJECT/LIVING_THING/INSECT"
LIVING_THING_OTHER = "NATURAL_OBJECT/LIVING_THING/LIVING_THING_OTHER"
MAMMAL = "NATURAL_OBJECT/LIVING_THING/MAMMAL"
MOLLUSC_ARTHROPOD = "NATURAL_OBJECT/LIVING_THING/MOLLUSC_ARTHROPOD"
REPTILE = "NATURAL_OBJECT/LIVING_THING/REPTILE"
LIVING_THING_PART = "NATURAL_OBJECT/LIVING_THING_PART"
ANIMAL_PART = "NATURAL_OBJECT/LIVING_THING_PART/ANIMAL_PART"
FLORA_PART = "NATURAL_OBJECT/LIVING_THING_PART/FLORA_PART"
LIVING_THING_PART_OTHER = "NATURAL_OBJECT/LIVING_THING_PART/LIVING_THING_PART_OTHER"
MINERAL = "NATURAL_OBJECT/MINERAL"
NATURAL_OBJECT_OTHER = "NATURAL_OBJECT/NATURAL_OBJECT_OTHER"
ORGANIZATION = "ORGANIZATION"
CORPORATION = "ORGANIZATION/CORPORATION"
COMPANY = "ORGANIZATION/CORPORATION/COMPANY"
COMPANY_GROUP = "ORGANIZATION/CORPORATION/COMPANY_GROUP"
CORPORATION_OTHER = "ORGANIZATION/CORPORATION/CORPORATION_OTHER"
ETHNIC_GROUP = "ORGANIZATION/ETHNIC_GROUP"
ETHNIC_GROUP_OTHER = "ORGANIZATION/ETHNIC_GROUP/ETHNIC_GROUP_OTHER"
NATIONALITY = "ORGANIZATION/ETHNIC_GROUP/NATIONALITY"
FAMILY = "ORGANIZATION/FAMILY"
INTERNATIONAL_ORGANIZATION = "ORGANIZATION/INTERNATIONAL_ORGANIZATION"
ORGANIZATION_OTHER = "ORGANIZATION/ORGANIZATION_OTHER"
POLITICAL_ORGANIZATION = "ORGANIZATION/POLITICAL_ORGANIZATION"
CABINET = "ORGANIZATION/POLITICAL_ORGANIZATION/CABINET"
GOVERNMENT = "ORGANIZATION/POLITICAL_ORGANIZATION/GOVERNMENT"
MILITARY = "ORGANIZATION/POLITICAL_ORGANIZATION/MILITARY"
POLITICAL_ORGANIZATION_OTHER = (
    "ORGANIZATION/POLITICAL_ORGANIZATION/POLITICAL_ORGANIZATION_OTHER"
)
POLITICAL_PARTY = "ORGANIZATION/POLITICAL_ORGANIZATION/POLITICAL_PARTY"
SHOW_ORGANIZATION = "ORGANIZATION/SHOW_ORGANIZATION"
SPORTS_ORGANIZATION = "ORGANIZATION/SPORTS_ORGANIZATION"
PRO_SPORTS_ORGANIZATION = "ORGANIZATION/SPORTS_ORGANIZATION/PRO_SPORTS_ORGANIZATION"
SPORTS_LEAGUE = "ORGANIZATION/SPORTS_ORGANIZATION/SPORTS_LEAGUE"
SPORTS_ORGANIZATION_OTHER = "ORGANIZATION/SPORTS_ORGANIZATION/SPORTS_ORGANIZATION_OTHER"
PERSON = "PERSON"
PRODUCT = "PRODUCT"
ART = "PRODUCT/ART"
ART_OTHER = "PRODUCT/ART/ART_OTHER"
BOOK = "PRODUCT/ART/BOOK"
BROADCAST_PROGRAM = "PRODUCT/ART/BROADCAST_PROGRAM"
MOVIE = "PRODUCT/ART/MOVIE"
MUSIC = "PRODUCT/ART/MUSIC"
PICTURE = "PRODUCT/ART/PICTURE"
SHOW = "PRODUCT/ART/SHOW"
AWARD = "PRODUCT/AWARD"
CHARACTER = "PRODUCT/CHARACTER"
CLASS = "PRODUCT/CLASS"
CLOTHING = "PRODUCT/CLOTHING"
DECORATION = "PRODUCT/DECORATION"
DOCTRINE_METHOD = "PRODUCT/DOCTRINE_METHOD"
ACADEMIC = "PRODUCT/DOCTRINE_METHOD/ACADEMIC"
CULTURE = "PRODUCT/DOCTRINE_METHOD/CULTURE"
DOCTRINE_METHOD_OTHER = "PRODUCT/DOCTRINE_METHOD/DOCTRINE_METHOD_OTHER"
MOVEMENT = "PRODUCT/DOCTRINE_METHOD/MOVEMENT"
PLAN = "PRODUCT/DOCTRINE_METHOD/PLAN"
RELIGION = "PRODUCT/DOCTRINE_METHOD/RELIGION"
SPORT = "PRODUCT/DOCTRINE_METHOD/SPORT"
STYLE = "PRODUCT/DOCTRINE_METHOD/STYLE"
THEORY = "PRODUCT/DOCTRINE_METHOD/THEORY"
DRUG = "PRODUCT/DRUG"
FOOD = "PRODUCT/FOOD"
DISH = "PRODUCT/FOOD/DISH"
FOOD_OTHER = "PRODUCT/FOOD/FOOD_OTHER"
ID_NUMBER = "PRODUCT/ID_NUMBER"
LANGUAGE = "PRODUCT/LANGUAGE"
LANGUAGE_OTHER = "PRODUCT/LANGUAGE/LANGUAGE_OTHER"
NATIONAL_LANGUAGE = "PRODUCT/LANGUAGE/NATIONAL_LANGUAGE"
MATERIAL = "PRODUCT/MATERIAL"
MONEY_FORM = "PRODUCT/MONEY_FORM"
OFFENCE = "PRODUCT/OFFENCE"
PRINTING = "PRODUCT/PRINTING"
MAGAZINE = "PRODUCT/PRINTING/MAGAZINE"
NEWSPAPER = "PRODUCT/PRINTING/NEWSPAPER"
PRINTING_OTHER = "PRODUCT/PRINTING/PRINTING_OTHER"
PRODUCT_OTHER = "PRODUCT/PRODUCT_OTHER"
RULE = "PRODUCT/RULE"
LAW = "PRODUCT/RULE/LAW"
RULE_OTHER = "PRODUCT/RULE/RULE_OTHER"
TREATY = "PRODUCT/RULE/TREATY"
SERVICE = "PRODUCT/SERVICE"
STOCK = "PRODUCT/STOCK"
TITLE = "PRODUCT/TITLE"
POSITION_VOCATION = "PRODUCT/TITLE/POSITION_VOCATION"
TITLE_OTHER = "PRODUCT/TITLE/TITLE_OTHER"
UNIT = "PRODUCT/UNIT"
CURRENCY = "PRODUCT/UNIT/CURRENCY"
UNIT_OTHER = "PRODUCT/UNIT/UNIT_OTHER"
VEHICLE = "PRODUCT/VEHICLE"
AIRCRAFT = "PRODUCT/VEHICLE/AIRCRAFT"
CAR = "PRODUCT/VEHICLE/CAR"
SHIP = "PRODUCT/VEHICLE/SHIP"
SPACESHIP = "PRODUCT/VEHICLE/SPACESHIP"
TRAIN = "PRODUCT/VEHICLE/TRAIN"
VEHICLE_OTHER = "PRODUCT/VEHICLE/VEHICLE_OTHER"
WEAPON = "PRODUCT/WEAPON"

ALL_LABELS = [
    COLOR,
    COLOR_OTHER,
    NATURE_COLOR,
    DISEASE,
    ANIMAL_DISEASE,
    DISEASE_OTHER,
    EVENT,
    EVENT_OTHER,
    INCIDENT,
    INCIDENT_OTHER,
    WAR,
    NATURAL_PHENOMENON,
    EARTHQUAKE,
    NATURAL_DISASTER,
    NATURAL_PHENOMENON_OTHER,
    OCCASION,
    CONFERENCE,
    GAME,
    OCCASION_OTHER,
    RELIGIOUS_FESTIVAL,
    FACILITY,
    ARCHAEOLOGICAL_PLACE,
    ARCHAEOLOGICAL_PLACE_OTHER,
    TUMULUS,
    FACILITY_OTHER,
    FACILITY_PART,
    GOE,
    AIRPORT,
    AMUSEMENT_PARK,
    CAR_STOP,
    GOE_OTHER,
    MARKET,
    MUSEUM,
    PARK,
    PORT,
    PUBLIC_INSTITUTION,
    RESEARCH_INSTITUTE,
    SCHOOL,
    SPORTS_FACILITY,
    STATION,
    THEATER,
    WORSHIP_PLACE,
    ZOO,
    LINE,
    BRIDGE,
    CANAL,
    LINE_OTHER,
    RAILROAD,
    ROAD,
    TUNNEL,
    WATER_ROUTE,
    GOD,
    LOCATION,
    ADDRESS,
    ADDRESS_OTHER,
    EMAIL,
    PHONE_NUMBER,
    POSTAL_ADDRESS,
    URL,
    ASTRAL_BODY,
    ASTRAL_BODY_OTHER,
    CONSTELLATION,
    PLANET,
    STAR,
    GEOLOGICAL_REGION,
    BAY,
    GEOLOGICAL_REGION_OTHER,
    ISLAND,
    LAKE,
    MOUNTAIN,
    RIVER,
    SEA,
    GPE,
    CITY,
    COUNTRY,
    COUNTY,
    GPE_OTHER,
    PROVINCE,
    LOCATION_OTHER,
    REGION,
    CONTINENTAL_REGION,
    DOMESTIC_REGION,
    REGION_OTHER,
    SPA,
    NAME_OTHER,
    NATURAL_OBJECT,
    COMPOUND,
    ELEMENT,
    LIVING_THING,
    AMPHIBIA,
    BIRD,
    FISH,
    FLORA,
    FUNGUS,
    INSECT,
    LIVING_THING_OTHER,
    MAMMAL,
    MOLLUSC_ARTHROPOD,
    REPTILE,
    LIVING_THING_PART,
    ANIMAL_PART,
    FLORA_PART,
    LIVING_THING_PART_OTHER,
    MINERAL,
    NATURAL_OBJECT_OTHER,
    ORGANIZATION,
    CORPORATION,
    COMPANY,
    COMPANY_GROUP,
    CORPORATION_OTHER,
    ETHNIC_GROUP,
    ETHNIC_GROUP_OTHER,
    NATIONALITY,
    FAMILY,
    INTERNATIONAL_ORGANIZATION,
    ORGANIZATION_OTHER,
    POLITICAL_ORGANIZATION,
    CABINET,
    GOVERNMENT,
    MILITARY,
    POLITICAL_ORGANIZATION_OTHER,
    POLITICAL_PARTY,
    SHOW_ORGANIZATION,
    SPORTS_ORGANIZATION,
    PRO_SPORTS_ORGANIZATION,
    SPORTS_LEAGUE,
    SPORTS_ORGANIZATION_OTHER,
    PERSON,
    PRODUCT,
    ART,
    ART_OTHER,
    BOOK,
    BROADCAST_PROGRAM,
    MOVIE,
    MUSIC,
    PICTURE,
    SHOW,
    AWARD,
    CHARACTER,
    CLASS,
    CLOTHING,
    DECORATION,
    DOCTRINE_METHOD,
    ACADEMIC,
    CULTURE,
    DOCTRINE_METHOD_OTHER,
    MOVEMENT,
    PLAN,
    RELIGION,
    SPORT,
    STYLE,
    THEORY,
    DRUG,
    FOOD,
    DISH,
    FOOD_OTHER,
    ID_NUMBER,
    LANGUAGE,
    LANGUAGE_OTHER,
    NATIONAL_LANGUAGE,
    MATERIAL,
    MONEY_FORM,
    OFFENCE,
    PRINTING,
    MAGAZINE,
    NEWSPAPER,
    PRINTING_OTHER,
    PRODUCT_OTHER,
    RULE,
    LAW,
    RULE_OTHER,
    TREATY,
    SERVICE,
    STOCK,
    TITLE,
    POSITION_VOCATION,
    TITLE_OTHER,
    UNIT,
    CURRENCY,
    UNIT_OTHER,
    VEHICLE,
    AIRCRAFT,
    CAR,
    SHIP,
    SPACESHIP,
    TRAIN,
    VEHICLE_OTHER,
    WEAPON,
]
