"""
This type stub file was generated by pyright.
"""

from __future__ import unicode_literals

from ._serialize import DocBin
from .doc import Doc
from .span import Span
from .token import Token

__all__ = ["Doc", "Token", "Span", "DocBin"]
