"""
This type stub file was generated by pyright.
"""

from __future__ import unicode_literals
from .matcher import Matcher  # type: ignore
from .phrasematcher import PhraseMatcher  # type: ignore
from .dependencymatcher import DependencyMatche  # type: ignore

__all__ = ["Matcher", "PhraseMatcher", "DependencyMatcher"]
