"""
This type stub file was generated by pyright.
"""

import plac
from pathlib import Path
from typing import Any, Optional

NEW_LABEL_THRESHOLD = 50
DEP_LABEL_THRESHOLD = 20
BLANK_MODEL_MIN_THRESHOLD = 100
BLANK_MODEL_THRESHOLD = 2000
@plac.annotations(
    lang=("model language", "positional", None, str),
    train_path=("location of JSON-formatted training data", "positional", None, Path),
    dev_path=("location of JSON-formatted development data", "positional", None, Path),
    base_model=("name of model to update (optional)", "option", "b", str),
    pipeline=(
        "Comma-separated names of pipeline components to train",
        "option",
        "p",
        str,
    ),
    ignore_warnings=("Ignore warnings, only show stats and errors", "flag", "IW", bool),
    verbose=("Print additional information and explanations", "flag", "V", bool),
    no_format=("Don't pretty-print the results", "flag", "NF", bool),
)
def debug_data(
    lang,
    train_path,
    dev_path,
    base_model: Optional[Any] = ...,
    pipeline=...,
    ignore_warnings: bool = ...,
    verbose: bool = ...,
    no_format: bool = ...,
):
    """
    Analyze, debug and validate your training and development data, get useful
    stats, and find problems like invalid entity annotations, cyclic
    dependencies, low data labels and more.
    """
    ...

def _load_file(file_path, msg): ...
def _compile_gold(train_docs, pipeline): ...
def _format_labels(labels, counts: bool = ...): ...
def _get_examples_without_label(data, label): ...
def _get_labels_from_model(nlp, pipe_name): ...
