"""
This type stub file was generated by pyright.
"""

import plac
from typing import Any, Optional
@plac.annotations(
    model=("Model to load", "positional", None, str),
    inputs=("Location of input file. '-' for stdin.", "positional", None, str),
    n_texts=("Maximum number of texts to use if available", "option", "n", int),
)
def profile(model, inputs: Optional[Any] = ..., n_texts=...):
    """
    Profile a spaCy pipeline, to find out which functions take the most time.
    Input should be formatted as one JSON object per line with a key "text".
    It can either be provided as a JSONL file, or be read from sys.sytdin.
    If no input file is specified, the IMDB dataset is loaded via Thinc.
    """
    ...

def parse_texts(nlp, texts): ...
def _read_inputs(loc, msg): ...
