"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

class Underscore(object):
    mutable_types = ...
    doc_extensions = ...
    span_extensions = ...
    token_extensions = ...
    def __init__(self, extensions, obj, start: Optional[Any] = ..., end: Optional[Any] = ...):
        ...
    
    def __dir__(self):
        ...
    
    def __getattr__(self, name):
        ...
    
    def __setattr__(self, name, value):
        ...
    
    def set(self, name, value):
        ...
    
    def get(self, name):
        ...
    
    def has(self, name):
        ...
    
    def _get_key(self, name):
        ...
    


def get_ext_args(**kwargs):
    """Validate and convert arguments. Reused in Doc, Token and Span."""
    ...

def is_writable_attr(ext):
    """Check if an extension attribute is writable.
    ext (tuple): The (default, getter, setter, method) tuple available  via
        {Doc,Span,Token}.get_extension.
    RETURNS (bool): Whether the attribute is writable.
    """
    ...

