"""
This type stub file was generated by pyright.
"""

from __future__ import unicode_literals
from .pipes import (
    DependencyParser,
    EntityLinker,
    EntityRecognizer,
    Pipe,
    Sentencizer,
    Tagger,
    Tensorizer,
    TextCategorizer,
)
from .morphologizer import Morphologizer  # type: ignore
from .entityruler import EntityRuler
from .hooks import SentenceSegmenter, SimilarityHook
from .functions import merge_entities, merge_noun_chunks, merge_subtokens

__all__ = [
    "Tagger",
    "DependencyParser",
    "EntityRecognizer",
    "EntityLinker",
    "TextCategorizer",
    "Tensorizer",
    "Pipe",
    "Morphologizer",
    "EntityRuler",
    "Sentencizer",
    "SentenceSegmenter",
    "SimilarityHook",
    "merge_entities",
    "merge_noun_chunks",
    "merge_subtokens",
]
