from typing import Dict, List
from spacy.tokens.doc import Doc
from .span import Span
from .token import Token

class Retokenizer:
    def __init__(self, doc: Doc) -> None: ...
    def __enter__(self) -> "Retokenizer": ...
    def __exit__(self, *args): ...
    def merge(self, span: Span, attrs: Dict = {}): ...
    def split(self, token: Token, orths: List, heads: List, attrs: Dict = {}): ...

