"""
This type stub file was generated by pyright.
"""

import sys
from spacy.cli import convert, debug_data, download, evaluate, info, init_model, link, package, pretrain, profile, train, validate

if __name__ == "__main__":
    commands = { "download": download,"link": link,"info": info,"train": train,"pretrain": pretrain,"debug-data": debug_data,"evaluate": evaluate,"convert": convert,"package": package,"init-model": init_model,"profile": profile,"validate": validate }
    command = sys.argv.pop(1)
