IS_ALPHA: int
IS_ASCII: int
IS_DIGIT: int
IS_LOWER: int
IS_PUNCT: int
IS_SPACE: int
IS_TITLE: int
IS_UPPER: int
LIKE_URL: int
LIKE_NUM: int
LIKE_EMAIL: int
IS_STOP: int
IS_OOV: int
IS_BRACKET: int
IS_QUOTE: int
IS_LEFT_PUNCT: int
IS_RIGHT_PUNCT: int
IS_CURRENCY: int

FLAG19: int
FLAG20: int
FLAG21: int
FLAG22: int
FLAG23: int
FLAG24: int
FLAG25: int
FLAG26: int
FLAG27: int
FLAG28: int
FLAG29: int
FLAG30: int
FLAG31: int
FLAG32: int
FLAG33: int
FLAG34: int
FLAG35: int
FLAG36: int
FLAG37: int
FLAG38: int
FLAG39: int
FLAG40: int
FLAG41: int
FLAG42: int
FLAG43: int
FLAG44: int
FLAG45: int
FLAG46: int
FLAG47: int
FLAG48: int
FLAG49: int
FLAG50: int
FLAG51: int
FLAG52: int
FLAG53: int
FLAG54: int
FLAG55: int
FLAG56: int
FLAG57: int
FLAG58: int
FLAG59: int
FLAG60: int
FLAG61: int
FLAG62: int
FLAG63: int

ID: int
ORTH: int
LOWER: int
NORM: int
SHAPE: int
PREFIX: int
SUFFIX: int

LENGTH: int
CLUSTER: int
LEMMA: int
POS: int
TAG: int
DEP: int
ENT_IOB: int
ENT_TYPE: int
ENT_ID: int
ENT_KB_ID: int
HEAD: int
SENT_START: int
SPACY: int
PROB: int
LANG: int
IDX: int

ADJ: int
ADP: int
ADV: int
AUX: int
CONJ: int
CCONJ: int
DET: int
INTJ: int
NOUN: int
NUM: int
PART: int
PRON: int
PROPN: int
PUNCT: int
SCONJ: int
SYM: int
VERB: int
X: int
EOL: int
SPACE: int

Animacy_anim: int
Animacy_inam: int
Animacy_hum: int
Animacy_nhum: int
Aspect_freq: int
Aspect_imp: int
Aspect_mod: int
Aspect_none: int
Aspect_perf: int
Aspect_iter: int
Aspect_hab: int
Case_abe: int
Case_abl: int
Case_abs: int
Case_acc: int
Case_ade: int
Case_all: int
Case_cau: int
Case_com: int
Case_cmp: int
Case_dat: int
Case_del: int
Case_dis: int
Case_ela: int
Case_equ: int
Case_ess: int
Case_gen: int
Case_ill: int
Case_ine: int
Case_ins: int
Case_loc: int
Case_lat: int
Case_nom: int
Case_par: int
Case_sub: int
Case_sup: int
Case_tem: int
Case_ter: int
Case_tra: int
Case_voc: int
Definite_two: int
Definite_def: int
Definite_red: int
Definite_cons: int
Definite_ind: int
Definite_spec: int
Degree_cmp: int
Degree_comp: int
Degree_none: int
Degree_pos: int
Degree_sup: int
Degree_abs: int
Degree_com: int
Degree_dim: int
Degree_equ: int
Evident_nfh: int
Gender_com: int
Gender_fem: int
Gender_masc: int
Gender_neut: int
Mood_cnd: int
Mood_imp: int
Mood_ind: int
Mood_n: int
Mood_pot: int
Mood_sub: int
Mood_opt: int
Mood_prp: int
Mood_adm: int
Negative_neg: int
Negative_pos: int
Negative_yes: int
Polarity_neg: int
Polarity_pos: int
Number_com: int
Number_dual: int
Number_none: int
Number_plur: int
Number_sing: int
Number_ptan: int
Number_count: int
Number_tri: int
NumType_card: int
NumType_dist: int
NumType_frac: int
NumType_gen: int
NumType_mult: int
NumType_none: int
NumType_ord: int
NumType_sets: int
Person_one: int
Person_two: int
Person_three: int
Person_none: int
Poss_yes: int
PronType_advPart: int
PronType_art: int
PronType_default: int
PronType_dem: int
PronType_ind: int
PronType_int: int
PronType_neg: int
PronType_prs: int
PronType_rcp: int
PronType_rel: int
PronType_tot: int
PronType_clit: int
PronType_exc: int
PronType_emp: int
Reflex_yes: int
Tense_fut: int
Tense_imp: int
Tense_past: int
Tense_pres: int
VerbForm_fin: int
VerbForm_ger: int
VerbForm_inf: int
VerbForm_none: int
VerbForm_part: int
VerbForm_partFut: int
VerbForm_partPast: int
VerbForm_partPres: int
VerbForm_sup: int
VerbForm_trans: int
VerbForm_conv: int
VerbForm_gdv: int
VerbForm_vnoun: int
Voice_act: int
Voice_cau: int
Voice_pass: int
Voice_mid: int
Voice_int: int
Voice_antip: int
Voice_dir: int
Voice_inv: int
Abbr_yes: int
AdpType_prep: int
AdpType_post: int
AdpType_voc: int
AdpType_comprep: int
AdpType_circ: int
AdvType_man: int
AdvType_loc: int
AdvType_tim: int
AdvType_deg: int
AdvType_cau: int
AdvType_mod: int
AdvType_sta: int
AdvType_ex: int
AdvType_adadj: int
ConjType_oper: int
ConjType_comp: int
Connegative_yes: int
Derivation_minen: int
Derivation_sti: int
Derivation_inen: int
Derivation_lainen: int
Derivation_ja: int
Derivation_ton: int
Derivation_vs: int
Derivation_ttain: int
Derivation_ttaa: int
Echo_rdp: int
Echo_ech: int
Foreign_foreign: int
Foreign_fscript: int
Foreign_tscript: int
Foreign_yes: int
Gender_dat_masc: int
Gender_dat_fem: int
Gender_erg_masc: int
Gender_erg_fem: int
Gender_psor_masc: int
Gender_psor_fem: int
Gender_psor_neut: int
Hyph_yes: int
InfForm_one: int
InfForm_two: int
InfForm_three: int
NameType_geo: int
NameType_prs: int
NameType_giv: int
NameType_sur: int
NameType_nat: int
NameType_com: int
NameType_pro: int
NameType_oth: int
NounType_com: int
NounType_prop: int
NounType_class: int
Number_abs_sing: int
Number_abs_plur: int
Number_dat_sing: int
Number_dat_plur: int
Number_erg_sing: int
Number_erg_plur: int
Number_psee_sing: int
Number_psee_plur: int
Number_psor_sing: int
Number_psor_plur: int
Number_pauc: int
Number_grpa: int
Number_grpl: int
Number_inv: int
NumForm_digit: int
NumForm_roman: int
NumForm_word: int
NumValue_one: int
NumValue_two: int
NumValue_three: int
PartForm_pres: int
PartForm_past: int
PartForm_agt: int
PartForm_neg: int
PartType_mod: int
PartType_emp: int
PartType_res: int
PartType_inf: int
PartType_vbp: int
Person_abs_one: int
Person_abs_two: int
Person_abs_three: int
Person_dat_one: int
Person_dat_two: int
Person_dat_three: int
Person_erg_one: int
Person_erg_two: int
Person_erg_three: int
Person_psor_one: int
Person_psor_two: int
Person_psor_three: int
Person_zero: int
Person_four: int
Polite_inf: int
Polite_pol: int
Polite_abs_inf: int
Polite_abs_pol: int
Polite_erg_inf: int
Polite_erg_pol: int
Polite_dat_inf: int
Polite_dat_pol: int
Polite_infm: int
Polite_form: int
Polite_form_elev: int
Polite_form_humb: int
Prefix_yes: int
PrepCase_npr: int
PrepCase_pre: int
PunctSide_ini: int
PunctSide_fin: int
PunctType_peri: int
PunctType_qest: int
PunctType_excl: int
PunctType_quot: int
PunctType_brck: int
PunctType_comm: int
PunctType_colo: int
PunctType_semi: int
PunctType_dash: int
Style_arch: int
Style_rare: int
Style_poet: int
Style_norm: int
Style_coll: int
Style_vrnc: int
Style_sing: int
Style_expr: int
Style_derg: int
Style_vulg: int
Style_yes: int
StyleVariant_styleShort: int
StyleVariant_styleBound: int
VerbType_aux: int
VerbType_cop: int
VerbType_mod: int
VerbType_light: int

PERSON: int
NORP: int
FACILITY: int
ORG: int
GPE: int
LOC: int
PRODUCT: int
EVENT: int
WORK_OF_ART: int
LANGUAGE: int

DATE: int
TIME: int
PERCENT: int
MONEY: int
QUANTITY: int
ORDINAL: int
CARDINAL: int

acomp: int
advcl: int
advmod: int
agent: int
amod: int
appos: int
attr: int
aux: int
auxpass: int
cc: int
ccomp: int
complm: int
conj: int
cop: int
csubj: int
csubjpass: int
dep: int
det: int
dobj: int
expl: int
hmod: int
hyph: int
infmod: int
intj: int
iobj: int
mark: int
meta: int
neg: int
nmod: int
nn: int
npadvmod: int
nsubj: int
nsubjpass: int
num: int
number: int
oprd: int
obj: int
obl: int
parataxis: int
partmod: int
pcomp: int
pobj: int
poss: int
possessive: int
preconj: int
prep: int
prt: int
punct: int
quantmod: int
rcmod: int
relcl: int
root: int
xcomp: int

acl: int
LAW: int
