# Automatically update CHANGELOG.md and create release when tag is pushed
name: Fire Release

on: 
  push:
    branches:

jobs:
  release:
    if: contains(github.event.head_commit.message, '[versionup]') == true && !(startsWith(github.event.ref, 'refs/tags'))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.TOKEN}}
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: tag
      shell: bash
      run: |
        TAG=$(git log -1 --pretty=%B | cut -f 4 -d" " | head -1)
        git tag $TAG
        git push origin $TAG
    - run: npm install github-release-notes -g
    - run: gren changelog --override --token ${{secrets.TOKEN}} 
    - run: gren release --override --token ${{secrets.TOKEN}}
    - name: commit
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git add .
        git commit -m "Update Changelog" && "nothing new to commit"
        git push github HEAD:${GITHUB_REF} && "nothing new to push"
