name: foo

on: 
  push:
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7]
        os: [ubuntu-latest, macos-latest]
        extras: [udify, elmo, none]
    steps:
    - name: Only for none
      if: 1 == 2
      run: echo "fooo"

    - name: Only for not none
      if: 1 == 1
      run: echo "barrr"
